import type { SubscriberArgs, SubscriberConfig } from "@medusajs/framework"
import * as fs from "fs"
import * as path from "path"

/**
 * AWB Generator Subscriber
 * 
 * Listens to order.placed events and auto-generates a Cargus AWB
 * if autoGenerateAwb is enabled in the Cargus config.
 * 
 * AWB is generated by calling the admin panel's Cargus API endpoint.
 */

const ADMIN_PANEL_URL = process.env.ADMIN_PANEL_URL || "http://127.0.0.1:3001"
const CARGUS_CONFIG_PATH = path.resolve(
  __dirname,
  "../../../../admin-panel/data/cargus-config.json"
)

interface CargusConfig {
  isActive: boolean
  autoGenerateAwb: boolean
}

function loadCargusConfig(): CargusConfig | null {
  try {
    // Try the relative path first (production layout)
    if (fs.existsSync(CARGUS_CONFIG_PATH)) {
      const raw = fs.readFileSync(CARGUS_CONFIG_PATH, "utf-8")
      return JSON.parse(raw)
    }
    // Fallback: absolute path
    const absolutePath = process.env.CARGUS_CONFIG_PATH || "/opt/qubitpage/current/admin-panel/data/cargus-config.json"
    if (fs.existsSync(absolutePath)) {
      const raw = fs.readFileSync(absolutePath, "utf-8")
      return JSON.parse(raw)
    }
    return null
  } catch (err) {
    console.error("[AWB Generator] Error reading Cargus config:", err)
    return null
  }
}

export default async function awbGeneratorHandler({
  event: { data },
  container,
}: SubscriberArgs<{ id: string }>) {
  const orderId = data.id
  console.log(`[AWB Generator] Processing order: ${orderId}`)

  try {
    // 1. Check Cargus config
    const config = loadCargusConfig()
    if (!config) {
      console.log("[AWB Generator] Cargus config not found, skipping AWB generation")
      return
    }

    if (!config.isActive) {
      console.log("[AWB Generator] Cargus integration is not active, skipping")
      return
    }

    if (!config.autoGenerateAwb) {
      console.log("[AWB Generator] Auto AWB generation is disabled, skipping")
      return
    }

    // 2. Check order metadata for courier preference
    const query = container.resolve("query") as {
      graph: (options: {
        entity: string
        fields: string[]
        filters: Record<string, unknown>
      }) => Promise<{ data: Array<{ id: string; metadata?: Record<string, unknown>; display_id?: number }> }>
    }

    const { data: orders } = await query.graph({
      entity: "order",
      fields: ["id", "display_id", "metadata"],
      filters: { id: orderId },
    })

    const order = orders[0]
    if (!order) {
      console.error(`[AWB Generator] Order not found: ${orderId}`)
      return
    }

    // Check if courier is set to cargus (or no courier set — default to cargus)
    const courier = (order.metadata as any)?.courier
    if (courier && courier !== "cargus") {
      console.log(`[AWB Generator] Order ${orderId} uses courier "${courier}", not cargus — skipping`)
      return
    }

    // Check if AWB already exists
    if ((order.metadata as any)?.awb_number) {
      console.log(`[AWB Generator] Order ${orderId} already has AWB: ${(order.metadata as any).awb_number}`)
      return
    }

    // Skip auto-AWB for bank transfer orders — admin must confirm payment manually first
    const paymentMethod = (order.metadata as any)?.payment_method
    if (paymentMethod === 'transfer') {
      console.log(`[AWB Generator] Order ${orderId} is bank transfer — skipping auto-AWB (admin must generate manually after confirming payment)`)
      return
    }

    // 3. Generate AWB via admin panel API
    console.log(`[AWB Generator] Auto-generating AWB for order #${order.display_id} (${orderId})`)

    // Small delay to ensure order is fully committed
    await new Promise((resolve) => setTimeout(resolve, 3000))

    const response = await fetch(`${ADMIN_PANEL_URL}/app/api/courier/cargus`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        action: "generate-awb",
        orderId: orderId,
      }),
    })

    const result = await response.json()

    if (result.success) {
      console.log(
        `[AWB Generator] SUCCESS: AWB ${result.awb} generated for order #${order.display_id}`
      )
    } else {
      console.error(
        `[AWB Generator] FAILED to generate AWB for order #${order.display_id}: ${result.error}`
      )
    }
  } catch (error) {
    console.error(`[AWB Generator] FATAL ERROR for order ${orderId}:`, error)
    if (error instanceof Error) {
      console.error(`[AWB Generator] Stack:`, error.stack)
    }
  }
}

export const config: SubscriberConfig = {
  event: "order.placed",
}
